### ISSUE TITLE
Status/Documenation

### ISSUE THREAD

**Issue by gordonbisnor** [rikas/zoho_hub#2]
Hello, wondering if this library is functional and if so, do you plan on releasing documentation? Or if you need help getting it running or writing docs, perhaps I could be of assistance. 

Looking to get up and running with API v2 well before they sunset V1 at the end of 2019!

**Comment by rikas** [comment]
Hi @gordonbisnor at the moment this only serves my needs in a project I'm currently working at. I had many requests to write proper documentation and make it more generic.

I'm working on it but I would definitely appreciate some help (because I don't have much time).

For example, I'm working with specific modules from Zoho and I guess some people would need different modules / custom modules.

**Comment by gordonbisnor** [comment]
Hey @rikas Thanks for getting back to me. Great so I will try to take a look at the library and see if I can add some documentation!

**Comment by jiblits** [comment]
I had to move Escarpment Labs over to the V2 API from a V1 client [zoho_crm](https://github.com/jiblits/zoho_crm) and this worked fairly well.

The application was integrated into a Rails application, so I could probably use some of the code there to provide examples of how to setup a Rails app to use this library.

I should note that right now I'm not using the OAuth 2 features of this library (I wrote all that myself before discovering this API client) however I can perhaps write up some basic docs.

Here's what I have in mind:

- `zoho_hub.rb` rails initializer
- Extending the models to include custom CRM attributes
- Basic use of the CRM modules

If this is cool, where would you like the docs to be added? The Readme is ok?

**Comment by rikas** [comment]
@jiblits For now lets add things into the Readme, yes, and thanks for the help.
